name: Tests

on:
  push:
    branches: [master]

jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run setup tests/test-1/data.json
      - run: |
          git config --global user.email "naccachefrederic@gmail.com"
          git config --global user.name "naccachefrederic"
          git add -A
          git commit -m "Added data.json"
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "naccachefrederic-hd-test-1"
          heroku_email: "naccachefrederic@gmail.com"
          appdir: "tests/test-1"
          env_file: ".env"
        env:
          HD_CHECK: "true"
      

